### ISSUE TITLE
Toolchain build failed

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [hermitcore/hermit-toolchain#25]
OS: Linux Opensuse Tumbleweed

I tried to build the Hermit toolchaing by following the readme, so I issued the command:
[build.log](https://github.com/hermitcore/hermit-toolchain/files/10032019/build.log)

`./toolchain.sh x86_64-hermit /home/yosu/Projects/IoT-NGIN/hermit-toolchain/`

My first attempt to compile the toolchain failed, so that the hermit-gcc compiler was not built (no one compiler was built in the bin folder indeed). After some logs analysis, I realized I missed to install some dependencies described in the readme, which I needed to find for Opensuse Tumbleweed:

- mpfr-devel-4.1.0-2.24.x86_64

- mpc-devel-1.2.1-1.25.x86_64

- gmp-devel-6.2.1-4.11.x86_64

Then, I tried again, but it failed, although the hermit-gcc compilers were built, apparently:

![image](https://user-images.githubusercontent.com/3658315/202460202-97f72827-deac-4948-b3e3-cbdcc0813c5f.png)

From built logs, I observed that the hermit compilers for Fortran and Go failed to be built,  I installed Opensuse packages for GCC Fortran and Go:
![image](https://user-images.githubusercontent.com/3658315/202460521-e8f6d403-3c28-4639-bfc2-9dfaaf1c1519.png)
![image](https://user-images.githubusercontent.com/3658315/202460676-142029af-1178-4c2e-bc76-400d86c1567a.png)

Next attempt to build the hermit toolchain still failed, with logs shown in attached build.log file.

I wonder if an specific version of gcc should be used (I have versions 11 and 12 installed) and how to select one for compilation

**Comment by mkroening** [comment]
Our [Dockerfile](https://github.com/hermitcore/hermit-toolchain/blob/575e92ff7d47a5b1bf65dc75090b6698007a339a/Dockerfile) uses Debian buster as its base (GCC 8.3.0). That version should work. Alternatively, you can disable go and fortran support in the [toolchain.sh](https://github.com/hermitcore/hermit-toolchain/blob/575e92ff7d47a5b1bf65dc75090b6698007a339a/toolchain.sh#LL146C30-L146C32).

In the long run, we should upgrade our [gcc fork](https://github.com/hermitcore/gcc).

**Comment by jesus-gorronogoitia** [comment]
Thanks a lot  @mkroening, I have two questions:
- how can I disable go and fortran support in toolchain.sh?
- how can I force to use a concrete gcc version in toolchain.sh?

**Comment by mkroening** [comment]
> * how can I disable go and fortran support in toolchain.sh?

Just remove them [here](https://github.com/hermitcore/hermit-toolchain/blob/575e92ff7d47a5b1bf65dc75090b6698007a339a/toolchain.sh#LL146C30-L146C40)

> * how can I force to use a concrete gcc version in toolchain.sh?

I'd guess by pointing the environment variable `CC` to the gcc executable of your choice.

> I also wonder if I can use a container created with your Dockerfile to build the toolchain and install it in a host volume, but I am not sure this installed tools would work provided that they had been compiled with a different gcc

I guess that should work. `/opt/hermit` in the Docker image should be mostly self-contained.

**Comment by jesus-gorronogoitia** [comment]
Thanks @mkroening I could build it with the docker image, and copy the container /opt/hermit in my host /opt/hermit.
Issue could be close.

**Comment by jesus-gorronogoitia** [comment]
After I had an incident with my laptop that required to reinstall the OS (Linux Opensuse Tumbleweed), I tried again to build the toolchain with the Docker image, by using this command:
`sudo docker build -t hermit/toolchain:1.0 .`
but I got a compilation error.
See attached docker_build.log

I am quite surprise as it worked before, I installed the same OS, and I assume docker build should be independent of the host OS.

Anyway, can you figure out what could be the cause of this problem.
I also wonder if you can build and deliver in GitHub a binary release for those, like me, who cannot build the toolchain.
Thank you so much in advance.
[docker_build.log](https://github.com/hermitcore/hermit-toolchain/files/10110358/docker_build.log)

**Comment by mkroening** [comment]
I identified the issue and opened https://github.com/hermitcore/libhermit-rs/issues/597.

You should be able to pull the container from [here](https://github.com/hermitcore/hermit-toolchain/pkgs/container/hermit-toolchain) once it has been pushed. Otherwise, building yourself should work as well once https://github.com/hermitcore/hermit-toolchain/pull/26 is merged.
