### ISSUE TITLE
Can not build toolchain - issue with hermit_rs

### ISSUE THREAD

**Issue by ELHorta** [hermitcore/hermit-toolchain#8]
After following the instructions:
$ git clone https://github.com/hermitcore/hermit-toolchain
$   sudo apt-get install nasm texinfo libmpfr-dev libmpc-dev libgmp-dev flex bison
$ . cmake/local-cmake.sh
$ ./toolchain.sh x86_64-hermit /home/ssrg/hermit | tee logtool_20220208.txt

I ended up with these errors:

-- Generating done
-- Build files have been written to: /home/ssrg/hermit-toolchain/build/tmp/hermit
Scanning dependencies of target hermit_rs
No such file or directory
make[3]: *** [librs/CMakeFiles/hermit_rs.dir/build.make:57: librs/CMakeFiles/hermit_rs] Error 1
make[2]: *** [CMakeFiles/Makefile2:313: librs/CMakeFiles/hermit_rs.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:219: librs/CMakeFiles/hermit-bootstrap.dir/rule] Error 2
make: *** [Makefile:223: hermit-bootstrap] Error 2

This is the info about my system:
Ubuntu 20.04.3 LTS
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Python 2.7.18
cmake version 3.7.2

I am attaching the entire log file here.
[logtool_20220208.txt](https://github.com/hermitcore/hermit-toolchain/files/8028450/logtool_20220208.txt)

Any clues?

**Comment by stlankes** [comment]
Hm, I will try to reproduce the error. Currently, I have no idea, why it fails.

**Comment by mkroening** [comment]
I can't reproduce your issue using an ubuntu:focal Docker container. 

Your log does not contain warnings and errors from stderr, which are needed to determine the cause of your issue. You can log stderr as well by redirecting stderr to stdout before piping to tee:
```
$ ./toolchain.sh x86_64-hermit /home/ssrg/hermit 2>&1 | tee logtool_20220208.txt
```

**Comment by mkroening** [comment]
I assume that `cargo` was not installed. Please reopen, if this does not fix your issue.
